site_name: Knotebook
nav:
  - Home: index.md
theme:
  name: material
  palette:
    - scheme: slate
extra:
  generator: false
plugins:
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      locale: en
      handlers:
        python:
          options:
            show_root_heading: false
            show_root_toc_entry: false
            show_if_no_docstring: true
            members_order: source
            separate_signature: true
            parameter_headings: true
            show_attribute_values: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            overloads_only: true
            show_bases: true
            show_source: false
            merge_init_into_class: true
            filters:
              - "!^__all__"
